[package]
name = "scrape-docs"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2021"

[dependencies]
reqwest = "0.11.20"
tokio = { version = "1.32.0", features = ["full"] }
select = "0.6.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
futures = "0.3.28"
